"""add last seen in user model

Revision ID: 810a79f28778
Revises: 44c64689c38e
Create Date: 2024-05-01 19:27:27.585782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810a79f28778'
down_revision = '44c64689c38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
